import color

CHASM = 0
DOWN_STAIRCASE = 10
UP_STAIRCASE = 11
DOWN_LADDER = 12
UP_LADDER = 13
RUSTED_WALL = 20
DIRTY_WALL = 21
WHITE_WALL = 22
WOOD_WALL = 23
DIRTY_FLOOR = 110
WHITE_FLOOR = 111
WOOD_FLOOR = 112

SIZE_MICRO = 0      # mouse-sized       0-1kg
SIZE_TINY = 1       # cat-sized         1-6kg
SIZE_SMALL = 2      # dog-sized         6-25kg
SIZE_MEDIUM = 3     # human-sized       25-100kg
SIZE_LARGE = 4      # deer-sized        100-400kg
SIZE_GIANT = 5      # bear-sized        400-1600kg

ICON_CORPSE = 5

ICON_IMPROVISED_BOMB = 256
ICON_IMPROVISED_MINE = 257
ICON_IMPROVISED_PISTOL = 258
ICON_IMPROVISED_SHOTGUN = 259
ICON_LASER_PISTOL = 260
ICON_LASER_MAGNUM = 261
ICON_LASER_RIFLE = 262
ICON_RAILGUN = 263
ICON_GRENADE_LAUNCHER = 264
ICON_SLING = 269
ICON_BOW = 270
ICON_ARROW = 271
ICON_LASER_SWORD = 272
ICON_LASER_KNIFE = 273
ICON_PNEUMATIC_SPEAR = 274
ICON_PNEUMATIC_AXE = 275
ICON_LASER_CLUB = 276
ICON_LASER_STAFF = 277
ICON_AUTO_RIFLE = 286
ICON_AUTO_PISTOL = 287
ICON_PISTOL = 292
ICON_MAGNUM = 293
ICON_SHOTGUN = 294
ICON_RIFLE = 295
ICON_CARBINE = 296
ICON_SNIPER = 297
ICON_GRENADE = 298
ICON_MINE = 299
ICON_AMMO_PISTOL = 300
ICON_AMMO_RIFLE = 301
ICON_AMMO_PELLET = 302
ICON_AMMO_SHOTGUN = 303
ICON_SWORD = 304
ICON_DAGGER = 305
ICON_HALBERD = 306
ICON_AXE = 307
ICON_BATON = 308
ICON_STAFF = 309
ICON_CLUB = 310
ICON_HAMMER = 311
ICON_LUCERNE = 312
ICON_SABER = 313
ICON_LONGSWORD = 314
ICON_ = 315
ICON_ = 316
ICON_SPEAR = 317
ICON_LANCE = 318
ICON_GLAIVE = 319

ICON_HERO = 320
ICON_SOLDIER = 321
ICON_WIZARD = 322
ICON_ROGUE = 323


MAT_POLYMER = 1
MAT_WOOD = 2
MAT_BONE = 3
MAT_CHITIN = 4
MAT_CERAMIC = 5
MAT_METAL = 6
MAT_KEVLAR = 7
MAT_ALLOY = 8
MAT_NANO = 9
MATERIALS_WEAPONS = ( MAT_POLYMER, MAT_WOOD, MAT_BONE, MAT_CHITIN, MAT_CERAMIC, MAT_METAL, MAT_ALLOY, MAT_NANO,)
MATERIALS_ARMOR = ( MAT_POLYMER, MAT_WOOD, MAT_BONE, MAT_CHITIN, MAT_CERAMIC, MAT_METAL, MAT_KEVLAR, MAT_ALLOY, MAT_NANO,)
MAT_COLORS = {
    MAT_POLYMER : color.polymer,
    MAT_WOOD    : color.wood,
    MAT_CHITIN  : color.chitin,
    MAT_BONE    : color.bone,
    MAT_CERAMIC : color.ceramic,
    MAT_METAL   : color.metal,
    MAT_KEVLAR  : color.kevlar,
    MAT_ALLOY   : color.alloy,
    MAT_NANO    : color.nano,
    }
MAT_NAMES = {
    MAT_POLYMER : "polymer",
    MAT_WOOD    : "wood",
    MAT_BONE    : "bone",
    MAT_CHITIN  : "chitin",
    MAT_CERAMIC : "ceramic",
    MAT_METAL   : "crumetal",
    MAT_KEVLAR  : "kevlar",
    MAT_ALLOY   : "alloy",
    MAT_NANO    : "nano",
    }
MAT_DURABILITY = {
    MAT_POLYMER : 0.75,
    MAT_WOOD    : 1,
    MAT_BONE    : 2,
    MAT_CHITIN  : 1.5,
    MAT_CERAMIC : 0.5,
    MAT_METAL   : 3,
    MAT_KEVLAR  : 6,
    MAT_ALLOY   : 9,
    MAT_NANO    : 32,
    }
MAT_ARMOR = {
    MAT_POLYMER : 0,
    MAT_WOOD    : 0,
    MAT_BONE    : 1,
    MAT_CHITIN  : 1,
    MAT_CERAMIC : 2,
    MAT_METAL   : 2,
    MAT_KEVLAR  : 2,
    MAT_ALLOY   : 3,
    MAT_NANO    : 4,
    }
MAT_DODGE = {
    MAT_POLYMER : 0,
    MAT_WOOD    : 1, # x2 for armor and weapons, x1 for hats
    MAT_BONE    : 2,
    MAT_CHITIN  : 3,
    MAT_CERAMIC : 1,
    MAT_METAL   : 0,
    MAT_KEVLAR  : 5,
    MAT_ALLOY   : 1,
    MAT_NANO    : 3,
    }
MAT_DAMAGE = {
    MAT_POLYMER : 2,
    MAT_WOOD    : 1,
    MAT_BONE    : 2,
    MAT_CHITIN  : 1,
    MAT_CERAMIC : 4,
    MAT_METAL   : 3,
    MAT_ALLOY   : 4,
    MAT_NANO    : 5,
    }
MAT_ATTACK = {
    MAT_POLYMER : 0,
    MAT_WOOD    : 5,
    MAT_BONE    : 10,
    MAT_CHITIN  : 15,
    MAT_CERAMIC : 15,
    MAT_METAL   : 20,
    MAT_ALLOY   : 25,
    MAT_NANO    : 30,
    }
MAT_VALUE = {
    MAT_POLYMER : 0,
    MAT_WOOD    : 0,
    MAT_BONE    : 1,
    MAT_CHITIN  : 1,
    MAT_CERAMIC : 2,
    MAT_METAL   : 2,
    MAT_KEVLAR  : 8,
    MAT_ALLOY   : 8,
    MAT_NANO    : 32,
    }
MAT_WEIGHT = {
    MAT_POLYMER : 1,
    MAT_WOOD    : 1.25,
    MAT_BONE    : 1.5,
    MAT_CHITIN  : 1,
    MAT_CERAMIC : 1.5,
    MAT_METAL   : 2,
    MAT_KEVLAR  : 1,
    MAT_ALLOY   : 1.75,
    MAT_NANO    : 0.75,
    }
MAT_SCARY = {
    MAT_POLYMER : 0,
    MAT_WOOD    : 0,
    MAT_BONE    : 1,
    MAT_CHITIN  : 1,
    MAT_CERAMIC : 2,
    MAT_METAL   : 2,
    MAT_KEVLAR  : 3,
    MAT_ALLOY   : 4,
    MAT_NANO    : 5,
    }
MAT_BEAUTY = {
    MAT_POLYMER : -1,
    MAT_WOOD    : 1,
    MAT_BONE    : 0,
    MAT_CHITIN  : 0,
    MAT_CERAMIC : 1,
    MAT_METAL   : 0,
    MAT_KEVLAR  : -1,
    MAT_ALLOY   : 1,
    MAT_NANO    : 2,
    }
MAT_THROW_RANGE = {
    MAT_POLYMER : -2,
    MAT_WOOD    : -1,
    MAT_BONE    : 0,
    MAT_CHITIN  : 0,
    MAT_CERAMIC : 0,
    MAT_METAL   : 0,
    MAT_ALLOY   : 1,
    MAT_NANO    : 2,
    }
CLASS_DAGGERS = 1
CLASS_SWORDS = 2
CLASS_HALBERDS = 3
CLASS_AXES = 4
CLASS_BATONS = 5
CLASS_STAVES = 6
CLASS_CLUBS = 7
CLASS_HAMMERS = 8
CLASS_LUCERNES = 9
CLASS_SABERS = 10
CLASS_SLINGS = 11
CLASS_BOWS = 12
CLASS_SPEARS = 13
CLASS_LANCES = 14
CLASS_GLAIVES = 15
CLASS_PISTOLS = 101
CLASS_REVOLVERS = 102
CLASS_SHOTGUNS = 103
CLASS_RIFLES = 104
CLASS_CARBINES = 105
CLASS_SNIPERS = 106
CLASS_GRENADES = 107
CLASS_MINES = 108

SLOTS_SHORTHAND = {
"mainhand" : "M",
"offhand" : "O",
"armor" : "W",
    }
